repos:
  - repo: local
    hooks:
      - id: run-tests-on-push
        name: Run pytest before pushing
        entry: pytest
        language: system
        types: [python]
        stages: [pre-push]
        always_run: true  # <--- Add this line
        pass_filenames: false  # <--- Prevents passing only staged files to pytest